"""
Merge programs.json + films.json + enrichment.json -> public/data.js

Sets `window.SIFF_DATA = { programs: [...], films: [...] }` in a single
static JS file. The site loads /data.js with no fetches and no CORS issues.

Run after parse_csv.py or after editing enrichment.json.
"""

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DATA = ROOT / "data"
PUB = ROOT / "public"


def main():
    programs = json.loads((DATA / "programs.json").read_text(encoding="utf-8"))
    films = json.loads((DATA / "films.json").read_text(encoding="utf-8"))
    enrichment = json.loads((DATA / "enrichment.json").read_text(encoding="utf-8"))

    # Merge enrichment onto films
    enriched = 0
    for f in films:
        e = enrichment.get(f["id"])
        if not e:
            continue
        for k, v in e.items():
            if k.startswith("_"):
                continue
            if v is None:
                continue
            f[k] = v
        enriched += 1

    payload = {
        "festival": {
            "edition": "28th SIFF",
            "edition_zh": "第28届上海国际电影节",
            "dates": "Jun 12 — Jun 21, 2026",
            "dates_zh": "2026年6月12日 — 6月21日",
        },
        "programs": programs,
        "films": films,
    }

    PUB.mkdir(parents=True, exist_ok=True)
    out = PUB / "data.js"
    out.write_text(
        "// AUTOGENERATED by scripts/build_data.py — do not edit by hand.\n"
        "window.SIFF_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )

    print(f"Wrote {out} ({out.stat().st_size:,} bytes)")
    print(f"  programs: {len(programs)}")
    print(f"  films:    {len(films)} ({enriched} with enrichment)")


if __name__ == "__main__":
    main()
