"""
Merge programs.json + films.json + enrichment_tmdb.json + enrichment.json
    -> public/data.js

Priority (highest wins): enrichment.json (hand-curated) > enrichment_tmdb.json
    (auto from TMDB) > skeleton fields from films.json.

Also derives `imdb_url` for every film:
   imdb_id present -> https://www.imdb.com/title/{id}/
   otherwise        -> https://www.imdb.com/find/?q={title}+{year}  (search fallback)

Sets `window.SIFF_DATA = { festival, programs, films }` in a single static
JS file. The site loads /data.js with no fetches and no CORS issues.

Run after parse_csv.py, enrich_from_tmdb.py, or after editing enrichment.json.
"""

import json
import urllib.parse
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DATA = ROOT / "data"
PUB = ROOT / "public"


def _load(path):
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {}


def main():
    programs = json.loads((DATA / "programs.json").read_text(encoding="utf-8"))
    films = json.loads((DATA / "films.json").read_text(encoding="utf-8"))
    enrichment = _load(DATA / "enrichment.json")           # hand-curated
    enrichment_tmdb = _load(DATA / "enrichment_tmdb.json") # auto

    # Merge order: TMDB first, then hand-curated overrides.
    enriched_count = 0
    for f in films:
        applied = False
        for source in (enrichment_tmdb, enrichment):
            e = source.get(f["id"])
            if not e:
                continue
            for k, v in e.items():
                if k.startswith("_"):
                    continue
                if v in (None, ""):
                    continue
                f[k] = v
                applied = True
        if applied:
            enriched_count += 1

        # Derive imdb_url for every film
        if f.get("imdb_id"):
            f["imdb_url"] = f"https://www.imdb.com/title/{f['imdb_id']}/"
        else:
            q_parts = [(f.get("title_en") or f.get("title_zh") or "").strip()]
            if f.get("year"):
                q_parts.append(str(f["year"]))
            q = urllib.parse.quote_plus(" ".join(p for p in q_parts if p))
            f["imdb_url"] = f"https://www.imdb.com/find/?q={q}&s=tt&ttype=ft"

    payload = {
        "festival": {
            "edition": "28th SIFF",
            "edition_zh": "第28届上海国际电影节",
            "dates": "Jun 12 — Jun 21, 2026",
            "dates_zh": "2026年6月12日 — 6月21日",
        },
        "programs": programs,
        "films": films,
    }
    enriched = enriched_count  # back-compat name not used outside this fn

    PUB.mkdir(parents=True, exist_ok=True)
    out = PUB / "data.js"
    out.write_text(
        "// AUTOGENERATED by scripts/build_data.py — do not edit by hand.\n"
        "window.SIFF_DATA = " + json.dumps(payload, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )

    with_imdb = sum(1 for f in films if f.get("imdb_id"))
    with_poster = sum(1 for f in films if f.get("poster_url"))

    print(f"Wrote {out} ({out.stat().st_size:,} bytes)")
    print(f"  programs:        {len(programs)}")
    print(f"  films:           {len(films)} ({enriched_count} enriched)")
    print(f"  films w/ imdb:   {with_imdb}")
    print(f"  films w/ poster: {with_poster}")


if __name__ == "__main__":
    main()
