// SIFF 2026 fictional film catalog
window.SIFF_FILMS = [
  {
    id: "lantern-hour",
    title: "Lantern Hour",
    titleZh: "灯笼时刻",
    director: "Wei Jiaqing",
    directorZh: "魏家清",
    country: "China",
    countryZh: "中国",
    year: 2026,
    runtime: 128,
    language: "Mandarin",
    section: "Golden Goblet",
    sectionZh: "金爵奖",
    premiere: "World Premiere",
    rating: "12+",
    tags: ["Drama", "Family"],
    synopsis: "On the last night of the Mid-Autumn Festival, a paper-lantern maker walks the alleys of old Hangzhou searching for his estranged son. A patient, watchful film about debts that never quite come due.",
    synopsisZh: "中秋的最后一夜，一位制灯老人在杭州老巷间寻找疏远多年的儿子。一部耐心而克制的电影，关于那些永远未能偿清的债。",
    screenings: [
      { date: "Jun 14", time: "19:30", venue: "Shanghai Film Art Center, Hall 1" },
      { date: "Jun 17", time: "13:00", venue: "SFC Shanghai Cinema, Hall 4" },
    ],
    stills: ["alley at dusk, two figures", "close-up: hands folding red paper", "wide: river at night with lanterns"],
    color: "#8a2a1f",
  },
  {
    id: "lake-no-name",
    title: "The Lake Has No Name",
    titleZh: "无名之湖",
    director: "Reina Satō",
    directorZh: "佐藤玲奈",
    country: "Japan",
    countryZh: "日本",
    year: 2026,
    runtime: 142,
    language: "Japanese",
    section: "Golden Goblet",
    sectionZh: "金爵奖",
    premiere: "International Premiere",
    rating: "15+",
    tags: ["Drama", "Mystery"],
    synopsis: "Three sisters return to their grandmother's cabin in Hokkaido after a thirty-year absence. The lake is the same. They are not.",
    synopsisZh: "三姐妹在三十年后重返北海道的祖母小屋。湖未改，人已非。",
    screenings: [
      { date: "Jun 15", time: "20:00", venue: "Shanghai Grand Theatre" },
      { date: "Jun 18", time: "15:30", venue: "Broadway Cinematheque" },
    ],
    stills: ["wide: silver lake, pine forest", "interior: three women at a low table", "fog over water at dawn"],
    color: "#3a4a5e",
  },
  {
    id: "salt-in-wind",
    title: "Salt in the Wind",
    titleZh: "风中的盐",
    director: "Soraya Daneshvar",
    directorZh: "索拉雅·丹尼什瓦尔",
    country: "Iran",
    countryZh: "伊朗",
    year: 2026,
    runtime: 109,
    language: "Persian",
    section: "Golden Goblet",
    sectionZh: "金爵奖",
    premiere: "Asian Premiere",
    rating: "15+",
    tags: ["Drama"],
    synopsis: "A salt harvester on Lake Urmia begins receiving letters addressed to a stranger. A modest, sun-bleached parable on inheritance and erasure.",
    synopsisZh: "乌尔米耶湖畔的盐工开始收到寄给陌生人的信件。一则朴素、被烈日漂白的关于继承与抹除的寓言。",
    screenings: [
      { date: "Jun 14", time: "16:00", venue: "Shanghai Film Art Center, Hall 2" },
      { date: "Jun 19", time: "21:00", venue: "UME International Cineplex" },
    ],
    stills: ["white salt flats, single figure", "envelope on cracked earth", "wide: dry lakebed at noon"],
    color: "#c8a86b",
  },
  {
    id: "cassette-days",
    title: "Cassette Days",
    titleZh: "卡带年代",
    director: "Park Jun-ho",
    directorZh: "朴俊昊",
    country: "South Korea",
    countryZh: "韩国",
    year: 2026,
    runtime: 116,
    language: "Korean",
    section: "Asian New Talent",
    sectionZh: "亚洲新人",
    premiere: "World Premiere",
    rating: "PG",
    tags: ["Coming-of-Age", "Music"],
    synopsis: "Busan, 1996. Two teenagers run a pirate radio show from a tiny apartment above a laundromat. A debut feature of unusual tenderness and rhythm.",
    synopsisZh: "1996年，釜山。两位少年在洗衣店楼上的小公寓里经营一档地下电台。一部异常温柔且节奏精准的处女作。",
    screenings: [
      { date: "Jun 16", time: "21:30", venue: "Shanghai Film Art Center, Hall 3" },
      { date: "Jun 20", time: "14:00", venue: "Pacific Cinema" },
    ],
    stills: ["teen at mic, headphones, fluorescent light", "stack of tapes, handwritten labels", "neon laundromat window at night"],
    color: "#d65a8f",
  },
  {
    id: "apricot-1999",
    title: "Apricot, 1999",
    titleZh: "杏花，1999",
    director: "Zhao Yifei",
    directorZh: "赵一飞",
    country: "China",
    countryZh: "中国",
    year: 2026,
    runtime: 134,
    language: "Mandarin",
    section: "Asian New Talent",
    sectionZh: "亚洲新人",
    premiere: "World Premiere",
    rating: "12+",
    tags: ["Drama", "Memory"],
    synopsis: "A schoolteacher in rural Shandong recalls the spring her village was first wired for electricity. Filmed across three apricot seasons.",
    synopsisZh: "山东乡间一位教师，回忆村庄第一次通电的那个春天。历时三个杏花季拍摄完成。",
    screenings: [
      { date: "Jun 15", time: "10:30", venue: "Shanghai Film Art Center, Hall 1" },
      { date: "Jun 21", time: "19:00", venue: "SFC Shanghai Cinema, Hall 2" },
    ],
    stills: ["apricot blossoms, school courtyard", "interior: oil lamp on table", "wide: dirt road with utility poles"],
    color: "#e8b8a8",
  },
  {
    id: "border-songs",
    title: "Border Songs",
    titleZh: "边界之歌",
    director: "Sutin Wongphan",
    directorZh: "苏廷·翁攀",
    country: "Thailand",
    countryZh: "泰国",
    year: 2026,
    runtime: 121,
    language: "Thai",
    section: "Belt & Road Film Week",
    sectionZh: "一带一路电影周",
    premiere: "World Premiere",
    rating: "15+",
    tags: ["Drama", "Music"],
    synopsis: "Along the Mekong, a karaoke bar owner books an act that may not be human. The director's most luminous work since 'Monsoon Mornings.'",
    synopsisZh: "湄公河畔，一家卡拉OK老板请来一位也许并非人类的歌手。导演自《雨季的早晨》以来最为光亮的作品。",
    screenings: [
      { date: "Jun 16", time: "22:00", venue: "Broadway Cinematheque" },
      { date: "Jun 18", time: "20:30", venue: "Yonghua Cinema" },
    ],
    stills: ["neon karaoke sign, river behind", "performer in spotlight, smoke", "wide: river barge at twilight"],
    color: "#2f6f6a",
  },
  {
    id: "heliopolis-88",
    title: "Heliopolis 88",
    titleZh: "赫利奥波利斯88",
    director: "Mariam Fawzy",
    directorZh: "玛丽亚姆·法齐",
    country: "Egypt",
    countryZh: "埃及",
    year: 2026,
    runtime: 97,
    language: "Arabic",
    section: "Belt & Road Film Week",
    sectionZh: "一带一路电影周",
    premiere: "Asian Premiere",
    rating: "15+",
    tags: ["Drama", "Historical"],
    synopsis: "Cairo, the summer before the wall fell. A switchboard operator at a state hotel listens too closely.",
    synopsisZh: "开罗，柏林墙倒塌前的那个夏天。一家国营酒店的总机接线员，听得太过仔细。",
    screenings: [
      { date: "Jun 17", time: "18:00", venue: "Shanghai Film Art Center, Hall 4" },
    ],
    stills: ["1980s hotel lobby, mirrored ceiling", "switchboard console, headset", "rooftop, satellite dishes"],
    color: "#b8843a",
  },
  {
    id: "carpenters-daughter",
    title: "The Carpenter's Daughter",
    titleZh: "木匠的女儿",
    director: "Nguyễn Lan",
    directorZh: "阮兰",
    country: "Vietnam",
    countryZh: "越南",
    year: 2026,
    runtime: 105,
    language: "Vietnamese",
    section: "Asian New Talent",
    sectionZh: "亚洲新人",
    premiere: "World Premiere",
    rating: "12+",
    tags: ["Drama"],
    synopsis: "In the Mekong Delta, a young woman inherits her father's workshop and his unfinished commission: a coffin for someone still alive.",
    synopsisZh: "湄公河三角洲，年轻女子继承了父亲的木工坊与一桩未完成的订单：为一位尚在人世的人打造棺木。",
    screenings: [
      { date: "Jun 19", time: "13:30", venue: "SFC Shanghai Cinema, Hall 3" },
    ],
    stills: ["workshop interior, sawdust, single bulb", "river skiff, woman seated", "close-up: hands planing wood"],
    color: "#6b4a2f",
  },
  {
    id: "glass-mountain",
    title: "Glass Mountain",
    titleZh: "玻璃山",
    director: "Lin Wei-cheng",
    directorZh: "林伟成",
    country: "Taiwan, China",
    countryZh: "中国台湾",
    year: 2026,
    runtime: 152,
    language: "Mandarin",
    section: "Spectrum",
    sectionZh: "展映",
    premiere: "Asian Premiere",
    rating: "15+",
    tags: ["Drama", "Epic"],
    synopsis: "Three generations of a Hakka family in Hsinchu, told through the glass factory they built, lost, and never quite let go of.",
    synopsisZh: "新竹一户客家三代人的故事，藉由他们建起、失去，却始终不能放手的玻璃厂诉说。",
    screenings: [
      { date: "Jun 14", time: "13:00", venue: "Shanghai Grand Theatre" },
      { date: "Jun 20", time: "10:00", venue: "UME International Cineplex" },
    ],
    stills: ["glass furnace, orange glow", "family portrait, formal, 1970s", "wide: factory ruins, overgrown"],
    color: "#5a3f2a",
  },
  {
    id: "cold-open",
    title: "Cold Open",
    titleZh: "冷场",
    director: "Joanna Werner",
    directorZh: "乔安娜·韦尔纳",
    country: "USA / France",
    countryZh: "美国／法国",
    year: 2026,
    runtime: 113,
    language: "English",
    section: "Spectrum",
    sectionZh: "展映",
    premiere: "Asian Premiere",
    rating: "15+",
    tags: ["Comedy", "Drama"],
    synopsis: "A washed-up SNL writer takes a job ghostwriting toasts for Manhattan weddings. The cringe is intentional and exact.",
    synopsisZh: "一位过气的喜剧编剧接下了为曼哈顿婚礼代写祝酒辞的工作。每一处尴尬都是有意为之。",
    screenings: [
      { date: "Jun 15", time: "21:30", venue: "Pacific Cinema" },
    ],
    stills: ["empty banquet hall, single mic", "writer at laptop, hotel desk", "wedding cake, hand reaching"],
    color: "#a8a8b8",
  },
  {
    id: "antlers-in-july",
    title: "Antlers in July",
    titleZh: "七月鹿角",
    director: "Tserendorj Bat",
    directorZh: "策仁多吉·巴特",
    country: "Mongolia",
    countryZh: "蒙古",
    year: 2026,
    runtime: 88,
    language: "Mongolian",
    section: "Belt & Road Film Week",
    sectionZh: "一带一路电影周",
    premiere: "World Premiere",
    rating: "PG",
    tags: ["Documentary"],
    synopsis: "A summer with a family of reindeer herders in the Khövsgöl taiga. Filmed across one velvet-shedding season, in patient long takes.",
    synopsisZh: "库苏古尔泰加林中，一户驯鹿牧人家庭的夏天。耐心的长镜头，记录鹿茸蜕落的一整季。",
    screenings: [
      { date: "Jun 18", time: "11:00", venue: "Shanghai Film Art Center, Hall 2" },
    ],
    stills: ["reindeer in mist, taiga", "child with bowl of milk", "wide: ger camp, mountains beyond"],
    color: "#7a8a6f",
  },
  {
    id: "notes-11th-floor",
    title: "Notes from the 11th Floor",
    titleZh: "十一楼记",
    director: "Yip Ka-fai",
    directorZh: "叶嘉辉",
    country: "Hong Kong, China",
    countryZh: "中国香港",
    year: 2026,
    runtime: 96,
    language: "Cantonese",
    section: "Spectrum",
    sectionZh: "展映",
    premiere: "Asian Premiere",
    rating: "15+",
    tags: ["Drama", "Urban"],
    synopsis: "A property surveyor inventories a Mong Kok walk-up on its last day. The tenants don't all want to be inventoried.",
    synopsisZh: "一位测量员在拆迁前最后一天走访旺角一栋唐楼。但并非所有租客都愿意被登记在册。",
    screenings: [
      { date: "Jun 16", time: "16:30", venue: "Broadway Cinematheque" },
      { date: "Jun 21", time: "13:00", venue: "Shanghai Film Art Center, Hall 3" },
    ],
    stills: ["narrow stairwell, fluorescent light", "old woman in doorway, mahjong tiles", "rooftop, laundry, cityscape"],
    color: "#4a5560",
  },
  {
    id: "aftermath-birthday",
    title: "Aftermath of a Birthday",
    titleZh: "生日之后",
    director: "Lucía Méndez",
    directorZh: "露西娅·门德斯",
    country: "Argentina",
    countryZh: "阿根廷",
    year: 2026,
    runtime: 102,
    language: "Spanish",
    section: "Spectrum",
    sectionZh: "展映",
    premiere: "Asian Premiere",
    rating: "15+",
    tags: ["Drama", "Family"],
    synopsis: "Buenos Aires. The morning after a sixtieth-birthday dinner, four siblings stay at the table long past the coffee.",
    synopsisZh: "布宜诺斯艾利斯。六十岁生日晚宴之后的清晨，四位手足在咖啡早已凉去之后仍未离席。",
    screenings: [
      { date: "Jun 17", time: "20:00", venue: "Yonghua Cinema" },
    ],
    stills: ["dinner table, leftover wine, dawn light", "sibling pair, garden, smoking", "kitchen, open window"],
    color: "#9a5a4a",
  },
  {
    id: "tin-can-symphony",
    title: "Tin Can Symphony",
    titleZh: "锡罐交响曲",
    director: "Aditya Wibowo",
    directorZh: "阿迪蒂亚·维博沃",
    country: "Indonesia",
    countryZh: "印度尼西亚",
    year: 2026,
    runtime: 84,
    language: "Indonesian",
    section: "Animation",
    sectionZh: "动画",
    premiere: "World Premiere",
    rating: "PG",
    tags: ["Animation", "Family"],
    synopsis: "A hand-drawn fable about a Jakarta street kid who conducts an orchestra of discarded tin cans. Two years in the making.",
    synopsisZh: "手绘寓言：一位雅加达街头少年指挥一支由废弃锡罐组成的乐团。耗时两年完成。",
    screenings: [
      { date: "Jun 15", time: "14:30", venue: "Pacific Cinema" },
      { date: "Jun 19", time: "10:30", venue: "SFC Shanghai Cinema, Hall 5" },
    ],
    stills: ["animated street, hand-drawn, watercolor", "boy with conductor's stick", "alley of tin cans, moonlight"],
    color: "#d4a02a",
  },
  {
    id: "pink-smoke",
    title: "Pink Smoke",
    titleZh: "粉色烟",
    director: "Anya Volkov",
    directorZh: "安雅·沃尔科夫",
    country: "Russia",
    countryZh: "俄罗斯",
    year: 2026,
    runtime: 119,
    language: "Russian",
    section: "Spectrum",
    sectionZh: "展映",
    premiere: "Asian Premiere",
    rating: "15+",
    tags: ["Drama"],
    synopsis: "Vladivostok, winter. A taxi driver, a port inspector, and a singer whose stage name no one remembers.",
    synopsisZh: "符拉迪沃斯托克的冬季。一位出租车司机，一位港口稽查员，以及一位无人记得艺名的歌手。",
    screenings: [
      { date: "Jun 18", time: "19:30", venue: "Shanghai Film Art Center, Hall 1" },
    ],
    stills: ["taxi interior, snow on windshield", "stage backstage, mirror lights", "harbor at night, ships"],
    color: "#d88aa0",
  },
  {
    id: "long-afternoon",
    title: "The Long Afternoon",
    titleZh: "漫长午后",
    director: "Chen Xiaoyu",
    directorZh: "陈晓宇",
    country: "China",
    countryZh: "中国",
    year: 2026,
    runtime: 167,
    language: "Mandarin",
    section: "Golden Goblet",
    sectionZh: "金爵奖",
    premiere: "World Premiere",
    rating: "15+",
    tags: ["Drama", "Epic"],
    synopsis: "Chongqing, summer of 2008. A pawn-shop clerk, a substitute teacher, and the slow elastic hours between two phone calls that change nothing and everything.",
    synopsisZh: "2008年夏，重庆。一位当铺职员，一位代课教师，以及在两通电话之间漫长、弹性的几个小时——什么都没改变，什么也都已改变。",
    screenings: [
      { date: "Jun 13", time: "19:00", venue: "Shanghai Grand Theatre" },
      { date: "Jun 22", time: "14:00", venue: "Shanghai Film Art Center, Hall 1" },
    ],
    stills: ["pawn shop counter, ceiling fan", "school corridor, monsoon light", "wide: hillside, river fog"],
    color: "#7a4530",
    featured: true,
  },
  {
    id: "ghost-train-yokohama",
    title: "Ghost Train, Yokohama",
    titleZh: "横滨幽灵列车",
    director: "Hideki Ono",
    directorZh: "小野秀树",
    country: "Japan",
    countryZh: "日本",
    year: 2026,
    runtime: 91,
    language: "Japanese",
    section: "Midnight",
    sectionZh: "午夜场",
    premiere: "Asian Premiere",
    rating: "18+",
    tags: ["Horror", "Genre"],
    synopsis: "A retired conductor returns to the Negishi line for one last shift. The 1:14 service has been out of timetable since 1973.",
    synopsisZh: "一位退休的列车长重返根岸线最后值勤。然而1:14那班车自1973年起便已不在时刻表上。",
    screenings: [
      { date: "Jun 16", time: "23:30", venue: "UME International Cineplex" },
    ],
    stills: ["empty train car, fluorescent flicker", "platform, fog, single figure", "conductor's cap on seat"],
    color: "#2a2a3a",
  },
  {
    id: "fishing-for-sun",
    title: "Fishing for the Sun",
    titleZh: "钓日",
    director: "Marco Cruz",
    directorZh: "马尔科·克鲁兹",
    country: "Philippines",
    countryZh: "菲律宾",
    year: 2026,
    runtime: 106,
    language: "Tagalog",
    section: "Documentary",
    sectionZh: "纪录片",
    premiere: "World Premiere",
    rating: "PG",
    tags: ["Documentary"],
    synopsis: "Three years with a single fishing crew off the Visayas coast. The sun rises 1,094 times. The catch shrinks each year.",
    synopsisZh: "三年时间，跟随一支维萨亚斯海岸的渔船。日出1094次，渔获逐年减少。",
    screenings: [
      { date: "Jun 17", time: "10:00", venue: "Shanghai Film Art Center, Hall 4" },
    ],
    stills: ["fishing boat at dawn, silhouettes", "nets being hauled, close-up", "wide: open sea, single boat"],
    color: "#e08a3a",
  },
  {
    id: "concrete-lullaby",
    title: "Concrete Lullaby",
    titleZh: "混凝土摇篮曲",
    director: "Frieda Lang",
    directorZh: "弗里达·朗",
    country: "Germany",
    countryZh: "德国",
    year: 2026,
    runtime: 124,
    language: "German",
    section: "Spectrum",
    sectionZh: "展映",
    premiere: "Asian Premiere",
    rating: "15+",
    tags: ["Drama"],
    synopsis: "Leipzig. A night-shift nurse in a brutalist maternity ward becomes obsessed with a building scheduled for demolition.",
    synopsisZh: "莱比锡。一位夜班护士供职于野兽派风格的妇产病房，渐渐对一栋即将拆除的建筑生出执念。",
    screenings: [
      { date: "Jun 20", time: "17:00", venue: "Yonghua Cinema" },
    ],
    stills: ["brutalist facade, dawn", "hospital corridor, empty gurney", "demolition fence, plaster dust"],
    color: "#7a7a78",
  },
  {
    id: "last-light-karakoram",
    title: "Last Light over Karakoram",
    titleZh: "喀喇昆仑最后之光",
    director: "Sara Iqbal",
    directorZh: "萨拉·伊克巴尔",
    country: "Pakistan",
    countryZh: "巴基斯坦",
    year: 2026,
    runtime: 115,
    language: "Urdu",
    section: "Belt & Road Film Week",
    sectionZh: "一带一路电影周",
    premiere: "World Premiere",
    rating: "12+",
    tags: ["Drama"],
    synopsis: "A border-post radio operator and a glaciologist share the same mountain for one impossible season.",
    synopsisZh: "一位边境哨所的无线电员，与一位冰川学家，在山中共度一个不可能的季节。",
    screenings: [
      { date: "Jun 15", time: "18:00", venue: "Shanghai Film Art Center, Hall 2" },
    ],
    stills: ["high-altitude camp, prayer flags", "radio console, frostbite hands", "wide: glacier, golden hour"],
    color: "#b8a070",
  },
  {
    id: "winter-light-restored",
    title: "Winter Light",
    titleZh: "冬日之光",
    director: "Bergman (restoration)",
    directorZh: "伯格曼（修复）",
    country: "Sweden",
    countryZh: "瑞典",
    year: 1963,
    runtime: 81,
    language: "Swedish",
    section: "4K Restoration",
    sectionZh: "4K修复",
    premiere: "Restored",
    rating: "All",
    tags: ["Classic", "Restoration"],
    synopsis: "A new 4K restoration of Bergman's chamber masterwork on doubt, supervised by the Swedish Film Institute. Print struck from the original camera negative.",
    synopsisZh: "瑞典电影学院监制，伯格曼室内剧杰作的全新4K修复版。由原始摄影机底片重制。",
    screenings: [
      { date: "Jun 19", time: "16:00", venue: "Shanghai Grand Theatre" },
    ],
    stills: ["church interior, winter light", "priest at altar, close-up", "snowy churchyard, single figure"],
    color: "#9aa4ad",
  },
  {
    id: "harbor-of-no-return",
    title: "Harbor of No Return",
    titleZh: "不归港",
    director: "Kim Min-jae",
    directorZh: "金敏宰",
    country: "South Korea",
    countryZh: "韩国",
    year: 2026,
    runtime: 137,
    language: "Korean",
    section: "Golden Goblet",
    sectionZh: "金爵奖",
    premiere: "World Premiere",
    rating: "15+",
    tags: ["Drama", "Crime"],
    synopsis: "Incheon, 1998. A customs officer and a smuggler's widow keep ledgers that don't quite match.",
    synopsisZh: "1998年，仁川。一位海关官员与一位走私者的遗孀，各自的账簿，彼此并不相符。",
    screenings: [
      { date: "Jun 14", time: "21:30", venue: "Shanghai Film Art Center, Hall 1" },
      { date: "Jun 18", time: "13:30", venue: "Pacific Cinema" },
    ],
    stills: ["customs warehouse, cargo crates", "widow at kitchen table, ledger", "harbor at night, container ship"],
    color: "#3f5566",
  },
  {
    id: "small-republic",
    title: "A Small Republic",
    titleZh: "小共和国",
    director: "Tom Verbeek",
    directorZh: "汤姆·维尔贝克",
    country: "Belgium",
    countryZh: "比利时",
    year: 2026,
    runtime: 99,
    language: "Flemish",
    section: "Documentary",
    sectionZh: "纪录片",
    premiere: "Asian Premiere",
    rating: "PG",
    tags: ["Documentary", "Politics"],
    synopsis: "A year inside the elected council of a Ghent housing estate. Democracy, in 2,400 square meters.",
    synopsisZh: "根特一栋公屋住户委员会，一年的内部记录。2400平方米中的民主。",
    screenings: [
      { date: "Jun 16", time: "11:30", venue: "Shanghai Film Art Center, Hall 4" },
    ],
    stills: ["council meeting, fluorescent room", "elevator interior, hand on button", "courtyard, children, laundry lines"],
    color: "#5a6a7a",
  },
  {
    id: "moth-orchard",
    title: "Moth Orchard",
    titleZh: "蛾园",
    director: "Liu Wenjing",
    directorZh: "刘文静",
    country: "China",
    countryZh: "中国",
    year: 2026,
    runtime: 76,
    language: "Mandarin",
    section: "Animation",
    sectionZh: "动画",
    premiere: "World Premiere",
    rating: "All",
    tags: ["Animation"],
    synopsis: "Ink-and-wash animated feature. A girl whose family tends a moth-orchard discovers a colony nobody has named yet.",
    synopsisZh: "水墨动画长片。家中经营蛾园的少女，发现了一群尚未被命名的蛾。",
    screenings: [
      { date: "Jun 20", time: "15:00", venue: "Shanghai Film Art Center, Hall 5" },
    ],
    stills: ["ink-wash trees, moths in flight", "girl in orchard, lantern", "close-up: moth on hand"],
    color: "#a89a78",
  },
];

window.SIFF_SECTIONS = [
  { id: "Golden Goblet", zh: "金爵奖", desc: "Main Competition" },
  { id: "Asian New Talent", zh: "亚洲新人", desc: "First and second features from across Asia" },
  { id: "Belt & Road Film Week", zh: "一带一路电影周", desc: "Films from countries along the route" },
  { id: "Spectrum", zh: "展映", desc: "International panorama" },
  { id: "Documentary", zh: "纪录片", desc: "Non-fiction selections" },
  { id: "Animation", zh: "动画", desc: "Hand-drawn, stop-motion, and digital animation" },
  { id: "4K Restoration", zh: "4K修复", desc: "Newly restored classics" },
  { id: "Midnight", zh: "午夜场", desc: "Genre, horror, the strange" },
];
